name = "Uttrson"
license = "MIT"
licenselink = "https://github.com/cluttrdev/uttrson/blob/master/LICENSE.md"
description = "A simple and minimalist theme for Hugo"
tags = ["blog", "responsive", "clean", "minimalist"]
features = ["blog", "responsive"]
min_version = "0.54.0"

[author]
    name = "cluttrdev"
    homepage = "https://cluttr.tech"

[original]
    name = "alexandrevicenzi"
    homepage = "http://alexandrevicenzi.com"
    repo = "https://github.com/alexandrevicenzi/soho"
